# -*- coding: utf-8 -*-
"""processData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EffjOnsouvMV2oi8AOgO-mcpXVNpUesF
"""

import pandas as pd
#get a list of disruption timestamps
disrupt = pd.read_csv('/content/drive/MyDrive/Hack Siemens/disruptions.csv')# put path to disruption
X_data = pd.read_csv('/content/drive/MyDrive/Hack Siemens/April-June.csv')# put path to disruption

# Python program to convert
# date to timestamp

def timify(date_str):
  import time
  import datetime


  string = date_str[8:10]+'/'+date_str[5:7]+'/'+date_str[0:4]
  print()
  #print(string)
  return int(time.mktime(datetime.datetime.strptime(string,
                        "%d/%m/%Y").timetuple()))+int(date_str[11:13])*24*60+int(date_str[14:16])*60+int(date_str[17:19])

dist_set = set(disrupt['DateTime'])
dist_set = [timify(str(e)) for e in dist_set]

april_june_dist_dates = []
for dis in dist_set:
  if dis >=timify('2021-04-01 00:00:00') and dis <=timify('2021-06-30 00:00:00'):
    april_june_dist_dates.append(dis)

april_june_dist_dates = [timify(str(e)) for e in april_june_dist_dates]

import numpy as np
D = np.array(len(X_data['DateTime'])*[0])
list_dates = list(X_data['DateTime'])
list_dates = [timify(str(e)) for e in list_dates]
for it in range(len(list_dates)):
  if list_dates[it] in april_june_dist_dates:
    D[it] = 1
    #print(list_dates[it])

X_data['Failure' ] = D
X_data['TS'] = list_dates

X_data

X_data.to_csv('/content/dataProcessed.csv', index=False)

X_data.Failure.sum()

